baseURL = 'https://troglodytto.github.io/'
languageCode = 'en-us'
title = "Piyush Upadhyay's Blog"
theme = "shibui"


[menu]
    [[menu.main]]
        name = "Zeno"
        url = "/posts/zeno"
        weight = 1
        identifier = "zeno"
        [menu.main.params]
          subtitle = "Writing an OS kernel in Rust"
          # draft = true
          # hidden = true

    [[menu.main]]
        name = "Hyperion"
        url = "/posts/hyperion"
        weight = 300
        identifier = "hyperion"
        [menu.main.params]
          subtitle = "Implementing the HTTP protocol from scratch"
          draft = true
          hidden = true

    [[menu.main]]
        name = "Beliefs"
        url = "/posts/beliefs"
        weight = 200
        identifier = "beliefs"
        [menu.main.params]
        subtitle = "Things I believe to be true"

[markup]
    [markup.highlight]
        style = "rose-pine-dawn"
        lineNos = true
        lineNumbersInTable = false
        noClasses = true


[caches]
  [caches.images]
    dir = ':cacheDir/images'
